const router = require('express').Router();

router.use('/auth',               require('./auth.routes'));
router.use('/ministries',         require('./ministries.routes'));
router.use('/sermons',            require('./sermons.routes'));
router.use('/events',             require('./events.routes'));
router.use('/announcements',      require('./announcements.routes'));
router.use('/prayer-requests',    require('./prayer.routes'));
router.use('/donations',          require('./donations.routes'));
router.use('/testimonials',       require('./testimonials.routes'));
router.use('/gallery',            require('./gallery.routes'));
router.use('/blog',               require('./blog.routes'));
router.use('/livestreams',        require('./livestream.routes'));
router.use('/contact',            require('./contact.routes'));
router.use('/volunteers',         require('./volunteers.routes'));
router.use('/volunteer-schedules',require('./volunteer-schedule.routes'));
router.use('/newsletter',         require('./newsletter.routes'));
router.use('/members',            require('./members.routes'));
router.use('/attendance',         require('./attendance.routes'));
router.use('/dashboard',          require('./dashboard.routes'));
router.use('/upload',             require('./upload.routes'));
router.use('/notifications',      require('./notifications.routes'));
router.use('/leadership',         require('./leadership.routes'));
router.use('/bible',              require('./bible.routes'));
router.use('/bookings',           require('./bookings.routes'));
router.use('/cell-groups',        require('./cellgroups.routes'));
router.use('/choir',              require('./choir.routes'));
router.use('/library',            require('./library.routes'));
router.use('/inventory',          require('./inventory.routes'));
router.use('/search',             require('./search.routes'));
router.use('/qr',                 require('./qr.routes'));
router.use('/roles',              require('./roles.routes'));
router.use('/projects',           require('./projects.routes'));
router.use('/ministry-tasks',     require('./ministry-tasks.routes'));
router.use('/workflow-templates', require('./workflow-templates.routes'));
router.use('/workflow-requests',  require('./workflow-requests.routes'));
router.use('/audit-logs',         require('./audit-logs.routes'));

module.exports = router;
